"""Installer CLI for the tiered Hermes memory provider.

Mirrors the mnemosyne-hermes install pattern: wrapper-mode install into
$HERMES_HOME/plugins/tiered/, status checks, and uninstall.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

PLUGIN_NAME = "tiered"


def hermes_home() -> Path:
    return Path(os.environ.get("HERMES_HOME") or "~/.hermes").expanduser()


def _resolve_package_dir() -> Path:
    return Path(__file__).resolve().parent


def plugin_target_dir(hermes_home_path: str | Path | None = None) -> Path:
    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    return base / "plugins" / PLUGIN_NAME


def _site_packages_for_python(python: Path) -> Path:
    result = subprocess.run(
        [str(python), "-c", "import sysconfig; print(sysconfig.get_paths()['purelib'])"],
        capture_output=True, text=True, timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Could not resolve site-packages for {python}")
    return Path(result.stdout.strip()).expanduser()


def install_plugin(
    *,
    hermes_home_path: str | Path | None = None,
    force: bool = False,
    python: str | Path | None = None,
) -> Path:
    """Install the tiered provider into Hermes' plugin directory (wrapper mode)."""
    source = _resolve_package_dir()
    if not source.is_dir():
        raise FileNotFoundError(f"tiered_hermes package not found at {source}")

    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    target = plugin_target_dir(hermes_home_path)

    if target.exists():
        if not force:
            raise FileExistsError(f"{target} exists. Use --force to replace.")
        if target.is_symlink():
            target.unlink()
        elif target.is_dir():
            shutil.rmtree(target)

    wrapper_python = Path(python).expanduser() if python else Path(sys.executable)
    site_pkg = _site_packages_for_python(wrapper_python)

    target.mkdir(parents=True, exist_ok=False)
    (target / "__init__.py").write_text(
        f'''"""Tiered memory provider — wrapper shim.

Generated by tiered-hermes install --mode wrapper.
"""
from __future__ import annotations

import site as _site

_PYTHON = {str(wrapper_python)!r}
_SITE = {str(site_pkg)!r}

_site.addsitedir(_SITE)

from tiered_hermes import *  # noqa: F401,F403,E402

# Hermes discovery markers (source-text scan, not import-based)
register_memory_provider  # defined in tiered_hermes.__init__
MemoryProvider = TieredMemoryProvider  # alias for discovery scan
''',
        encoding="utf-8",
    )

    # Copy plugin.yaml
    source_yaml = source / "plugin.yaml"
    if source_yaml.is_file():
        shutil.copy2(source_yaml, target / "plugin.yaml")

    return target


def status(*, hermes_home_path: str | Path | None = None) -> int:
    target = plugin_target_dir(hermes_home_path)
    if not target.exists():
        print("Status: NOT INSTALLED")
        return 1
    init_file = target / "__init__.py"
    if not init_file.is_file():
        print("Status: BROKEN (no __init__.py)")
        return 1
    print("Status: INSTALLED")
    print(f"  Path: {target}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="tiered-hermes",
        description="Install the tiered memory provider for Hermes Agent.",
    )
    parser.add_argument("--hermes-home", help="Hermes home directory")
    subp = parser.add_subparsers(dest="command")

    inst = subp.add_parser("install", help="Install into Hermes plugin directory")
    inst.add_argument("--force", action="store_true")
    inst.add_argument("--python", help="Python interpreter for wrapper mode")

    subp.add_parser("status", help="Show install status")
    subp.add_parser("uninstall", help="Remove from Hermes plugin directory")

    args = parser.parse_args(argv)
    cmd = args.command or "install"

    try:
        if cmd == "install":
            target = install_plugin(
                hermes_home_path=args.hermes_home,
                force=args.force,
                python=args.python,
            )
            print(f"Installed. Wrapper at {target}")
            print("Done. Next: hermes config set memory.provider tiered")
            return 0
        elif cmd == "status":
            return status(hermes_home_path=args.hermes_home)
        elif cmd == "uninstall":
            target = plugin_target_dir(args.hermes_home)
            if target.exists():
                if target.is_symlink():
                    target.unlink()
                else:
                    shutil.rmtree(target)
                print(f"Removed: {target}")
            return 0
        else:
            parser.print_help()
            return 1
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
